spring.application.name=demo
# Canviar la ruta de la interficie de usuari de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Canviar la ruta de la definicio JSON de la API
springdoc.api-docs.path=/api-docs

spring.data.mongodb.uri=mongodb+srv://user:1234@cluster0.q8wrgdr.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=ReservasAjedrez

##crear Indexs a la BD
spring.data.mongodb.auto-index-creation=true

jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=86400000